version: '3.1'

services:

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    #restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PASS}"
    volumes:
      - ./wp:/var/www/html
      - ./sql:/sql
    links:
      - db:mysql

  db:
    image: mysql:latest
    #restart: always
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]    
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql

  wpcli:
     image: wordpress:cli
     #restart: always
     depends_on:
       - wordpress
       - db
     volumes:
       - ./wp:/var/www/html
       - ./sql:/sql

  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    #restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_USER: "${DB_USER}"
      PMA_PASSWORD: "${DB_PASS}"
